openapi: 3.1.0
info:
  version: 1.0.0
  title: Recepies app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Auth
    description: Authentication and registration
  - name: Users
    description: User information
  - name: Categories
    description: Recipe categories
  - name: Ingredients
    description: Ingredients
  - name: Recipes
    description: Recipes
servers:
  - url: http://localhost:3000
  - url: https://dcgroup-react-node.onrender.com
paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
