openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipes app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of recipes app

tags:
  - name: Auth
    description: Authentication and registration
  - name: Users
    description: User information
  - name: Categories
    description: Recipe categories
  - name: Ingredients
    description: Ingredients
  - name: Recipes
    description: Recipes

servers:
  - url: http://localhost:3000
  - url: https://dcgroup-react-node-b.onrender.com

paths:
  /api/recipes:
    post:
      operationId: createRecipe
      tags: [Recipes]
      summary: Create a new recipe
      description: Private endpoint (JWT). Creates a new user recipe.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: ../swagger/components/schemas/RecipeInput.yaml
          application/json:
            schema:
              $ref: ../swagger/components/schemas/RecipeInput.yaml
      responses:
        '201':
          $ref: ../swagger/components/responses/201.yaml
        '400':
          $ref: ../swagger/components/responses/400.yaml
        '401':
          $ref: ../swagger/components/responses/401.yaml
        '500':
          $ref: ../swagger/components/responses/500.yaml
  /api/users/current:
    get:
      $ref: ../swagger/path/usersCurrent/get.yaml
  /api/categories:
    get: 
      $ref: '../swagger/path/categories/get.yaml'
  /api/ingredients:
    get: 
      $ref: '../swagger/path/ingredients/get.yaml'
  /api/recipes/{id}:
    get:
      $ref: '../swagger/path/recipes/{id}/get.yaml'

  /api/recipes/own:
    get:
      $ref: '../swagger/path/recipes/own/get.yaml'
  /api/recipes/saved-recipes:
    post:
      $ref: '../swagger/path/recipes/postSavedRecipes.yaml'
  /api/recipes/saved-recipes/{recipeId}:
    delete:
      $ref: '../swagger/path/recipes/{id}/deleteSavedRecipe.yaml'

  /api/auth/register:
    post:
      $ref: '../swagger/path/auth/register/post.yaml'

  /api/auth/login:
    post:
      $ref: '../swagger/path/auth/login/post.yaml'

  /api/auth/logout:
    post:
      $ref: '../swagger/path/auth/logout/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RecipeIngredient:
      $ref: ../swagger/components/schemas/RecipeIngredient.yaml

    Recipe:
      $ref: ../swagger/components/schemas/Recipe.yaml

    OwnRecipesResponse:
      $ref: ../swagger/components/schemas/OwnRecipesResponse.yaml
