openapi: 3.1.0
info:
  version: 1.0.0
  title: Recepies app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Recipes app
tags:
  - name: Auth
    description: Authentication and registration
  - name: Users
    description: User information
  - name: Categories
    description: Recipe categories
  - name: Ingredients
    description: Ingredients
  - name: Recipes
    description: Recipes
servers:
  - url: http://localhost:3000
  - url: https://dcgroup-react-node-b.onrender.com
paths:
/api/recipes:
  post:
    tags: [Recipes]
    summary: Create a new recipe
    description: Private endpoint (JWT). Creates a new user recipe.
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: ../swagger/components/schemas/RecipeInput.yaml
    responses:
      '201':
        description: Recipe created
      '400':
        $ref: ../swagger/components/responses/400.yaml
      '401':
        $ref: ../swagger/components/responses/401.yaml
      '500':
        $ref: ../swagger/components/responses/500.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
