type: object
required:
  - title
  - description
  - time
  - category
  - ingredients
  - instructions
  - owner
  - createdAt
properties:
  id:
    type: string
    description: Recipe ObjectId
    example: '64628af74c3d0ddd28897fcd'
  title:
    type: string
    maxLength: 64
    example: 'Battenberg Cake'
  description:
    type: string
    maxLength: 200
    example: 'A classic British cake made with almond sponge cake and covered with marzipan.'
  time:
    type: string
    description: 'Cooking time in minutes (stored as a string in DB)'
    example: '60'
  category:
    type: string
    description: 'Human-readable category name from DB'
    example: 'Dessert'
  area:
    type: string
    nullable: true
    description: 'Cuisine/area; optional'
    example: 'British'
  instructions:
    type: string
    maxLength: 1200
    example: 'Heat oven to 180C/160C fan... line the base and sides...'
  thumb:
    type: string
    format: uri
    nullable: true
    description: "Image URL (field name in DB is 'thumb')"
    example: 'https://ftp.goit.study/img/so-yummy/preview/Battenberg%20Cake.jpg'
  ingredients:
    type: array
    items:
      $ref: './RecipeIngredient.yaml'
  owner:
    type: string
    description: 'Owner ObjectId'
    example: '64c8d958249fae54bae90bb9'
  createdAt:
    type: string
    format: date-time
    example: '2023-03-11T19:25:33.243+00:00'
  updatedAt:
    type: string
    format: date-time
    example: '2024-03-03T22:47:51.976+00:00'
