type: object
required:
  - name
  - decr
  - cookiesTime
  - category
  - ingredients
  - instruction
  - owner
  - createdAt
properties:
  id:
    type: string
    example: '66b8e6b2f1c8a5f2d1a9c222'
  name:
    type: string
    maxLength: 64
    example: 'Pasta Carbonara'
  decr:
    type: string
    maxLength: 200
    example: 'Classic Italian pasta with eggs, cheese and pancetta'
  cookiesTime:
    type: integer
    minimum: 1
    maximum: 360
    example: 25
    description: time in minutes
  cals:
    type: integer
    minimum: 1
    maximum: 10000
    example: 450
  category:
    type: string
    example: '66b8e6b2f1c8a5f2d1a9c777'
    description: ID from the category collection
  ingredients:
    type: array
    items:
      $ref: './RecipeIngredient.yaml'
  instruction:
    type: string
    maxLength: 1200
    example: 'Boil pasta, fry pancetta, mix with eggs and cheese...'
  recipeImg:
    type: string
    format: uri
    example: 'https://cdn.example.com/images/recipe.jpg'
  owner:
    type: string
    example: '66b8e6b2f1c8a5f2d1a9c999'
  createdAt:
    type: string
    format: date-time
    example: '2025-08-20T12:34:56.000Z'
